export const enum EControls {
  Up = 'up',
  Down = 'down',
  Left = 'left',
  Right = 'right',
  Escape = 'escape',
  Restart = 'restart',
  Backpack = 'backpack',
  Enter = 'enter',
  Digit1 = 'digit1',
  Digit2 = 'digit2',
  Digit3 = 'digit3',
  Digit4 = 'digit4',
  Digit5 = 'digit5',
  Digit6 = 'digit6',
  Digit7 = 'digit7',
  Digit8 = 'digit8',
  Digit9 = 'digit9',
}
